import type { Metadata } from "next";
import "./globals.css";
import { Mochiy_Pop_One } from "next/font/google";

const mochiyPopOne = Mochiy_Pop_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=M+PLUS+1p&family=M+PLUS+2:wght@100..900&family=Mochiy+Pop+One&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={mochiyPopOne.className}>{children}</body>
    </html>
  );
}
